#!/usr/bin/env python3

import argparse
import hashlib
import re
import sys
from pathlib import Path


EXPECTED_COUNT = 163
EXPECTED_SOURCE_COUNTS = (17, 146)
EXPECTED_UTF16_UNITS = 1674
EXPECTED_FIRST_SCALAR_COUNT = 12
EXPECTED_SINGLETONS = (0x1F6D8, 0x1FA8A, 0x1FA8E, 0x1FAC8, 0x1FACD, 0x1FAEA, 0x1FAEF)
EXPECTED_CANONICAL_SHA256 = "2501eb2716ba14088393e0bfb5d78aaa0db923176999351d9e81ce373748c54c"

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SEQUENCE_SOURCES = (
    REPOSITORY_ROOT / "Source/JavaScriptCore/ucd/emoji-sequences.txt",
    REPOSITORY_ROOT / "Source/JavaScriptCore/ucd/emoji-zwj-sequences.txt",
)
TEST262_SOURCE = REPOSITORY_ROOT / "JSTests/test262/test/built-ins/RegExp/unicodeSets/generated/rgi-emoji-17.0.js"
OUTPUT = REPOSITORY_ROOT / "Source/WebCore/platform/graphics/cocoa/DriftstackEmoji17Sequences.h"


def read_ucd_sequences(path: Path) -> list[tuple[int, ...]]:
    result = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not re.search(r"#\s*E17\.0\b", line):
            continue
        code_points = tuple(int(value, 16) for value in line.split(";", 1)[0].split())
        if not code_points:
            raise ValueError(f"empty Emoji 17.0 sequence in {path}")
        result.append(code_points)
    return result


def decode_javascript_unicode_literal(value: str) -> tuple[int, ...]:
    result = []
    position = 0
    pattern = re.compile(r"\\u(?:\{([0-9A-Fa-f]+)\}|([0-9A-Fa-f]{4}))")
    while position < len(value):
        match = pattern.match(value, position)
        if not match:
            raise ValueError(f"unsupported Test262 string literal fragment: {value[position:]!r}")
        result.append(int(match.group(1) or match.group(2), 16))
        position = match.end()
    return tuple(result)


def read_test262_sequences(path: Path) -> list[tuple[int, ...]]:
    source = path.read_text(encoding="utf-8")
    match = re.search(r"matchStrings:\s*\[(.*?)\]\s*,?\n\s*\}\);", source, re.DOTALL)
    if not match:
        raise ValueError(f"could not find matchStrings in {path}")
    literals = re.findall(r'"((?:\\.|[^"\\])*)"', match.group(1))
    return [decode_javascript_unicode_literal(value) for value in literals]


def canonicalize(sequences: list[tuple[int, ...]]) -> list[tuple[int, ...]]:
    return sorted(set(sequences))


def canonical_bytes(sequences: list[tuple[int, ...]]) -> bytes:
    lines = (" ".join(f"{code_point:X}" for code_point in sequence) for sequence in sequences)
    return ("\n".join(lines) + "\n").encode("ascii")


def cpp_literal(sequence: tuple[int, ...]) -> str:
    pieces = []
    for code_point in sequence:
        if code_point <= 0xFFFF:
            pieces.append(f"\\u{code_point:04X}")
        else:
            pieces.append(f"\\U{code_point:08X}")
    return 'u"' + "".join(pieces) + '"'


HEADER_PREFIX = """// Copyright (C) 2026 Driftstack. All rights reserved.
//
// This file is generated by Tools/Scripts/generate-driftstack-emoji17-sequences.py.
// Do not edit it directly.
//
// Inputs: Unicode 17.0 emoji-sequences.txt + emoji-zwj-sequences.txt, independently
// checked against Test262's generated RGI_Emoji 17.0 corpus.
// Canonical sequence seal: SHA-256 2501eb2716ba14088393e0bfb5d78aaa0db923176999351d9e81ce373748c54c.

#pragma once

#include <CoreText/CoreText.h>
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <optional>
#include <span>
#include <string_view>
#include <wtf/RetainPtr.h>
#include <wtf/text/StringView.h>

namespace WebCore {

// Emoji 17 coverage is capture-proven only for the exact Safari 26.4 band.
// Keep this predicate independent of the font/config corpus: all archetypes
// currently share one bundled TTC, while their observable coverage does not.
// Read the environment at each use so a long-lived process cannot retain an
// archetype decision across a test or session transition.
inline constexpr bool driftstackEmoji17ArchetypeSupportsCoverage(std::string_view archetype)
{
    constexpr std::string_view suffix = "_safari26_4";
    return archetype.size() >= suffix.size()
        && archetype.substr(archetype.size() - suffix.size()) == suffix;
}

static_assert(driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_4"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage(""));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone16pro_ios18_6_safari18_6"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17pro_ios18_7_safari26_0"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17pro_ios18_7_safari26_3"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_5"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_40"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_chrome150"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_4_extra"));

inline bool driftstackEmoji17EnabledForCurrentArchetype()
{
    const char* archetype = std::getenv("DRIFTSTACK_ARCHETYPE");
    return archetype && driftstackEmoji17ArchetypeSupportsCoverage(archetype);
}

inline constexpr std::array<std::u16string_view, 163> driftstackEmoji17Sequences { {
"""


HEADER_SUFFIX = """inline bool driftstackMayStartEmoji17Sequence(std::span<const char16_t> characters, size_t offset = 0)
{
    if (offset > characters.size() || characters.size() - offset < 2)
        return false;
    char32_t lead = characters[offset];
    char32_t trail = characters[offset + 1];
    if (lead < 0xD800 || lead > 0xDBFF || trail < 0xDC00 || trail > 0xDFFF)
        return false;
    char32_t firstScalar = 0x10000 + ((lead - 0xD800) << 10) + (trail - 0xDC00);
    for (auto candidate : driftstackEmoji17FirstScalars) {
        if (candidate == firstScalar)
            return true;
    }
    return false;
}

inline bool driftstackMayStartEmoji17Sequence(StringView characters)
{
    return !characters.is8Bit() && driftstackMayStartEmoji17Sequence(characters.span16());
}

inline bool driftstackEmoji17SequenceMatchesAt(std::span<const char16_t> characters, size_t offset, std::u16string_view candidate)
{
    if (offset > characters.size() || candidate.size() > characters.size() - offset)
        return false;
    for (size_t i = 0; i < candidate.size(); ++i) {
        if (characters[offset + i] != candidate[i])
            return false;
    }
    return true;
}

inline size_t driftstackEmoji17SequenceLengthAt(std::span<const char16_t> characters, size_t offset)
{
    if (!driftstackMayStartEmoji17Sequence(characters, offset))
        return 0;
    size_t longestMatch = 0;
    for (auto candidate : driftstackEmoji17Sequences) {
        if (candidate.size() > longestMatch && driftstackEmoji17SequenceMatchesAt(characters, offset, candidate))
            longestMatch = candidate.size();
    }
    return longestMatch;
}

inline bool driftstackIsEmoji17Sequence(std::span<const char16_t> characters)
{
    if (!driftstackMayStartEmoji17Sequence(characters))
        return false;
    for (auto candidate : driftstackEmoji17Sequences) {
        if (candidate.size() == characters.size() && driftstackEmoji17SequenceMatchesAt(characters, 0, candidate))
            return true;
    }
    return false;
}

inline bool driftstackIsEmoji17Sequence(StringView characters)
{
    return !characters.is8Bit() && driftstackIsEmoji17Sequence(characters.span16());
}

// A draw run can contain adjacent grapheme clusters which all use the same
// bundled emoji face. Recognize only complete concatenations of the exact 163
// additions; mixed or partial text fails open to the ordinary shaping path.
inline size_t driftstackEmoji17SequenceRunCount(std::span<const char16_t> characters)
{
    if (characters.empty())
        return 0;
    size_t offset = 0;
    size_t count = 0;
    while (offset < characters.size()) {
        size_t longestMatch = driftstackEmoji17SequenceLengthAt(characters, offset);
        if (!longestMatch)
            return 0;
        offset += longestMatch;
        ++count;
    }
    return count;
}

inline size_t driftstackEmoji17SequenceRunCount(StringView characters)
{
    return characters.is8Bit() ? 0 : driftstackEmoji17SequenceRunCount(characters.span16());
}

enum class DriftstackAppleColorEmojiFace : uint8_t {
    None,
    Public,
    Ui,
};

inline DriftstackAppleColorEmojiFace driftstackAppleColorEmojiFace(CTFontRef font)
{
    if (!font)
        return DriftstackAppleColorEmojiFace::None;
    RetainPtr familyName = adoptCF(CTFontCopyFamilyName(font));
    if (!familyName)
        return DriftstackAppleColorEmojiFace::None;
    if (CFStringCompare(familyName.get(), CFSTR(".Apple Color Emoji UI"), kCFCompareCaseInsensitive) == kCFCompareEqualTo)
        return DriftstackAppleColorEmojiFace::Ui;
    if (CFStringCompare(familyName.get(), CFSTR("Apple Color Emoji"), kCFCompareCaseInsensitive) == kCFCompareEqualTo)
        return DriftstackAppleColorEmojiFace::Public;
    return DriftstackAppleColorEmojiFace::None;
}

inline bool driftstackIsBundledAppleColorEmojiFont(CTFontRef font)
{
    if (driftstackAppleColorEmojiFace(font) == DriftstackAppleColorEmojiFace::None)
        return false;
    RetainPtr<CFTypeRef> attribute = adoptCF(CTFontCopyAttribute(font, kCTFontURLAttribute));
    if (!attribute || CFGetTypeID(attribute.get()) != CFURLGetTypeID())
        return false;
    RetainPtr fileName = adoptCF(CFURLCopyLastPathComponent(static_cast<CFURLRef>(attribute.get())));
    return fileName && CFStringCompare(fileName.get(), CFSTR("AppleColorEmoji-160px.ttc"), kCFCompareCaseInsensitive) == kCFCompareEqualTo;
}

inline bool driftstackIsBundledAppleColorEmojiUIFont(CTFontRef font)
{
    return driftstackAppleColorEmojiFace(font) == DriftstackAppleColorEmojiFace::Ui
        && driftstackIsBundledAppleColorEmojiFont(font);
}

inline float driftstackPublicAppleColorEmojiAdvance(float pointSize)
{
    const unsigned pointPixelSize = static_cast<unsigned>(pointSize + 0.5f);
    if (pointPixelSize >= 26)
        return pointSize;
    switch (pointPixelSize) {
    case 8: return 11.f;
    case 9: return 12.f;
    case 10: return 13.f;
    case 11: return 15.f;
    case 12: return 16.f;
    case 13: return 17.f;
    case 14: return 19.f;
    case 15: return 20.f;
    case 16: return 21.f;
    case 17: return 22.f;
    case 18: return 22.f;
    case 19: return 23.f;
    case 20: return 23.f;
    case 21: return 23.f;
    case 22: return 24.f;
    case 23: return 24.f;
    case 24: return 25.f;
    case 25: return 26.f;
    default: return pointSize <= 12.f ? 16.f * (pointSize / 12.f) : pointSize;
    }
}

struct DriftstackEmojiUIGeometry {
    float advance { 0 };
    float ascent { 0 };
    float descent { 0 };
    float leading { 0 };

    explicit operator bool() const { return advance > 0; }
};

struct DriftstackEmojiUIGeometryCacheEntry {
    float pointSize { 0 };
    DriftstackEmojiUIGeometry geometry;
    bool initialized { false };
};

// Resolve a pre-Emoji-17 color scalar through the host system cascade. This
// yields the hidden `.Apple Color Emoji UI` face and, crucially, its contextual
// tracking. The bundled face1 has the same outlines but loses that UI geometry
// when materialized directly, so the host run is the canonical geometry probe.
inline DriftstackEmojiUIGeometry driftstackComputeSystemEmojiUIGeometry(float pointSize)
{
    RetainPtr systemFont = adoptCF(CTFontCreateUIFontForLanguage(kCTFontUIFontSystem, pointSize, nullptr));
    if (!systemFont)
        return { };

    static constexpr std::array<UniChar, 2> probeCharacters { 0xD83C, 0xDF89 }; // U+1F389 PARTY POPPER
    RetainPtr probeString = adoptCF(CFStringCreateWithCharacters(kCFAllocatorDefault, probeCharacters.data(), probeCharacters.size()));
    if (!probeString)
        return { };

    const void* attributeKeys[] = { kCTFontAttributeName };
    const void* attributeValues[] = { systemFont.get() };
    RetainPtr attributes = adoptCF(CFDictionaryCreate(kCFAllocatorDefault, attributeKeys, attributeValues, 1, &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks));
    RetainPtr attributedString = adoptCF(CFAttributedStringCreate(kCFAllocatorDefault, probeString.get(), attributes.get()));
    RetainPtr<CTLineRef> line;
    if (attributedString)
        line = adoptCF(CTLineCreateWithAttributedString(attributedString.get()));
    if (!line)
        return { };

    CFArrayRef runs = CTLineGetGlyphRuns(line.get());
    if (!runs || CFArrayGetCount(runs) != 1)
        return { };
    auto run = static_cast<CTRunRef>(CFArrayGetValueAtIndex(runs, 0));
    CFDictionaryRef runAttributes = CTRunGetAttributes(run);
    auto runFont = static_cast<CTFontRef>(CFDictionaryGetValue(runAttributes, kCTFontAttributeName));
    if (driftstackAppleColorEmojiFace(runFont) != DriftstackAppleColorEmojiFace::Ui)
        return { };

    CGFloat ascent = 0;
    CGFloat descent = 0;
    CGFloat leading = 0;
    double advance = CTLineGetTypographicBounds(line.get(), &ascent, &descent, &leading);
    if (!(advance > 0))
        return { };
    return {
        static_cast<float>(advance),
        static_cast<float>(ascent),
        static_cast<float>(descent),
        static_cast<float>(leading),
    };
}

inline DriftstackEmojiUIGeometry driftstackSystemEmojiUIGeometry(float pointSize)
{
    if (!(pointSize > 0))
        return { };

    // Font initialization, shaping, and painting ask for the same geometry in
    // tight succession. Keep a small bounded cache per rendering thread: it
    // avoids repeating the CoreText line construction, needs no cross-thread
    // lock, and cannot grow with attacker-controlled CSS font sizes.
    static thread_local std::array<DriftstackEmojiUIGeometryCacheEntry, 32> cache;
    static thread_local size_t nextSlot = 0;
    for (const auto& entry : cache) {
        if (entry.initialized && entry.pointSize == pointSize)
            return entry.geometry;
    }

    auto geometry = driftstackComputeSystemEmojiUIGeometry(pointSize);
    cache[nextSlot] = { pointSize, geometry, true };
    nextSlot = (nextSlot + 1) % cache.size();
    return geometry;
}

inline std::optional<float> driftstackEmoji17TargetAdvance(CTFontRef font, float pointSize)
{
    if (!driftstackEmoji17EnabledForCurrentArchetype()
        || !(pointSize > 0) || !driftstackIsBundledAppleColorEmojiFont(font))
        return std::nullopt;
    if (driftstackAppleColorEmojiFace(font) == DriftstackAppleColorEmojiFace::Public)
        return driftstackPublicAppleColorEmojiAdvance(pointSize);
    auto geometry = driftstackSystemEmojiUIGeometry(pointSize);
    if (geometry)
        return geometry.advance;
    return std::nullopt;
}

} // namespace WebCore
"""


def generate_header(sequences: list[tuple[int, ...]]) -> str:
    entries = "".join(f"    std::u16string_view {{ {cpp_literal(sequence)} }},\n" for sequence in sequences)
    first_scalars = sorted({sequence[0] for sequence in sequences})
    first_scalar_lines = "".join(
        "    " + ", ".join(f"0x{value:X}" for value in first_scalars[offset:offset + 6]) + ",\n"
        for offset in range(0, len(first_scalars), 6)
    )
    first_scalar_array = (
        "} };\n\n"
        f"inline constexpr std::array<char32_t, {len(first_scalars)}> driftstackEmoji17FirstScalars {{ {{\n"
        + first_scalar_lines
        + "} };\n\n"
    )
    return HEADER_PREFIX + entries + first_scalar_array + HEADER_SUFFIX


def validated_sequences() -> list[tuple[int, ...]]:
    source_sequences = [read_ucd_sequences(path) for path in SEQUENCE_SOURCES]
    source_counts = tuple(len(sequences) for sequences in source_sequences)
    if source_counts != EXPECTED_SOURCE_COUNTS:
        raise ValueError(f"unexpected per-source Emoji 17.0 counts: {source_counts}")

    sequences = canonicalize([sequence for group in source_sequences for sequence in group])
    if len(sequences) != EXPECTED_COUNT:
        raise ValueError(f"expected {EXPECTED_COUNT} unique Emoji 17.0 sequences, found {len(sequences)}")

    utf16_units = sum(1 if code_point <= 0xFFFF else 2 for sequence in sequences for code_point in sequence)
    if utf16_units != EXPECTED_UTF16_UNITS:
        raise ValueError(f"expected {EXPECTED_UTF16_UNITS} Emoji 17.0 UTF-16 units, found {utf16_units}")

    first_scalars = {sequence[0] for sequence in sequences}
    if len(first_scalars) != EXPECTED_FIRST_SCALAR_COUNT:
        raise ValueError(f"expected {EXPECTED_FIRST_SCALAR_COUNT} Emoji 17.0 first scalars, found {len(first_scalars)}")

    singletons = tuple(sequence[0] for sequence in sequences if len(sequence) == 1)
    if singletons != EXPECTED_SINGLETONS:
        raise ValueError(f"unexpected Emoji 17.0 singleton set: {singletons!r}")

    digest = hashlib.sha256(canonical_bytes(sequences)).hexdigest()
    if digest != EXPECTED_CANONICAL_SHA256:
        raise ValueError(f"canonical Emoji 17.0 seal mismatch: {digest}")

    test262_sequences = canonicalize(read_test262_sequences(TEST262_SOURCE))
    if test262_sequences != sequences:
        missing = set(sequences) - set(test262_sequences)
        extra = set(test262_sequences) - set(sequences)
        raise ValueError(f"Test262 parity mismatch: missing={len(missing)} extra={len(extra)}")
    return sequences


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Driftstack's exact Emoji 17.0 sequence matcher")
    parser.add_argument("--check", action="store_true", help="fail if the checked-in header is stale")
    parser.add_argument("--stdout", action="store_true", help="print the generated header without writing it")
    arguments = parser.parse_args()

    generated = generate_header(validated_sequences())
    if arguments.stdout:
        sys.stdout.write(generated)
        return 0
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"error: {OUTPUT.relative_to(REPOSITORY_ROOT)} is stale; regenerate with {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
