// Copyright (C) 2026 Driftstack. All rights reserved.
//
// This file is generated by Tools/Scripts/generate-driftstack-emoji17-sequences.py.
// Do not edit it directly.
//
// Inputs: Unicode 17.0 emoji-sequences.txt + emoji-zwj-sequences.txt, independently
// checked against Test262's generated RGI_Emoji 17.0 corpus.
// Canonical sequence seal: SHA-256 2501eb2716ba14088393e0bfb5d78aaa0db923176999351d9e81ce373748c54c.

#pragma once

#include <CoreText/CoreText.h>
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <optional>
#include <span>
#include <string_view>
#include <wtf/RetainPtr.h>
#include <wtf/text/StringView.h>

namespace WebCore {

// Emoji 17 coverage is capture-proven only for the exact Safari 26.4 band.
// Keep this predicate independent of the font/config corpus: all archetypes
// currently share one bundled TTC, while their observable coverage does not.
// Read the environment at each use so a long-lived process cannot retain an
// archetype decision across a test or session transition.
inline constexpr bool driftstackEmoji17ArchetypeSupportsCoverage(std::string_view archetype)
{
    constexpr std::string_view suffix = "_safari26_4";
    return archetype.size() >= suffix.size()
        && archetype.substr(archetype.size() - suffix.size()) == suffix;
}

static_assert(driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_4"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage(""));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone16pro_ios18_6_safari18_6"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17pro_ios18_7_safari26_0"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17pro_ios18_7_safari26_3"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_5"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_40"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_chrome150"));
static_assert(!driftstackEmoji17ArchetypeSupportsCoverage("iphone17_ios18_7_safari26_4_extra"));

inline bool driftstackEmoji17EnabledForCurrentArchetype()
{
    const char* archetype = std::getenv("DRIFTSTACK_ARCHETYPE");
    return archetype && driftstackEmoji17ArchetypeSupportsCoverage(archetype);
}

inline constexpr std::array<std::u16string_view, 163> driftstackEmoji17Sequences { {
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001F430\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001F430\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001F430\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001F430\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001FAEF\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001FAEF\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001FAEF\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F468\U0001F3FB\u200D\U0001FAEF\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001F430\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001F430\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001F430\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001F430\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001FAEF\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001FAEF\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001FAEF\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F468\U0001F3FC\u200D\U0001FAEF\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001F430\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001F430\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001F430\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001F430\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001FAEF\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001FAEF\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001FAEF\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F468\U0001F3FD\u200D\U0001FAEF\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001F430\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001F430\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001F430\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001F430\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001FAEF\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001FAEF\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001FAEF\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FE\u200D\U0001FAEF\u200D\U0001F468\U0001F3FF" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001F430\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001F430\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001F430\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001F430\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001FAEF\u200D\U0001F468\U0001F3FB" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001FAEF\u200D\U0001F468\U0001F3FC" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001FAEF\u200D\U0001F468\U0001F3FD" },
    std::u16string_view { u"\U0001F468\U0001F3FF\u200D\U0001FAEF\u200D\U0001F468\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001F430\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001F430\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001F430\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001F430\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001FAEF\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001FAEF\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001FAEF\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FB\u200D\U0001FAEF\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001F430\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001F430\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001F430\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001F430\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001FAEF\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001FAEF\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001FAEF\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FC\u200D\U0001FAEF\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001F430\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001F430\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001F430\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001F430\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001FAEF\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001FAEF\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001FAEF\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FD\u200D\U0001FAEF\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001F430\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001F430\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001F430\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001F430\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001FAEF\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001FAEF\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001FAEF\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FE\u200D\U0001FAEF\u200D\U0001F469\U0001F3FF" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001F430\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001F430\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001F430\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001F430\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001FAEF\u200D\U0001F469\U0001F3FB" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001FAEF\u200D\U0001F469\U0001F3FC" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001FAEF\u200D\U0001F469\U0001F3FD" },
    std::u16string_view { u"\U0001F469\U0001F3FF\u200D\U0001FAEF\u200D\U0001F469\U0001F3FE" },
    std::u16string_view { u"\U0001F46F\U0001F3FB" },
    std::u16string_view { u"\U0001F46F\U0001F3FB\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FB\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FC" },
    std::u16string_view { u"\U0001F46F\U0001F3FC\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FC\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FD" },
    std::u16string_view { u"\U0001F46F\U0001F3FD\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FD\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FE" },
    std::u16string_view { u"\U0001F46F\U0001F3FE\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FE\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FF" },
    std::u16string_view { u"\U0001F46F\U0001F3FF\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F46F\U0001F3FF\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F6D8" },
    std::u16string_view { u"\U0001F93C\U0001F3FB" },
    std::u16string_view { u"\U0001F93C\U0001F3FB\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FB\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FC" },
    std::u16string_view { u"\U0001F93C\U0001F3FC\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FC\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FD" },
    std::u16string_view { u"\U0001F93C\U0001F3FD\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FD\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FE" },
    std::u16string_view { u"\U0001F93C\U0001F3FE\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FE\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FF" },
    std::u16string_view { u"\U0001F93C\U0001F3FF\u200D\u2640\uFE0F" },
    std::u16string_view { u"\U0001F93C\U0001F3FF\u200D\u2642\uFE0F" },
    std::u16string_view { u"\U0001F9D1\u200D\U0001FA70" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001F430\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001F430\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001F430\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001F430\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001FA70" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001F9D1\U0001F3FB\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001F430\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001F430\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001F430\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001F430\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001FA70" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001F9D1\U0001F3FC\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001F430\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001F430\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001F430\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001F430\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001FA70" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001F9D1\U0001F3FD\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001F430\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001F430\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001F430\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001F430\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001FA70" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FE\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FF" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001F430\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001F430\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001F430\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001F430\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001FA70" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FB" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FC" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FD" },
    std::u16string_view { u"\U0001F9D1\U0001F3FF\u200D\U0001FAEF\u200D\U0001F9D1\U0001F3FE" },
    std::u16string_view { u"\U0001FA8A" },
    std::u16string_view { u"\U0001FA8E" },
    std::u16string_view { u"\U0001FAC8" },
    std::u16string_view { u"\U0001FACD" },
    std::u16string_view { u"\U0001FAEA" },
    std::u16string_view { u"\U0001FAEF" },
} };

inline constexpr std::array<char32_t, 12> driftstackEmoji17FirstScalars { {
    0x1F468, 0x1F469, 0x1F46F, 0x1F6D8, 0x1F93C, 0x1F9D1,
    0x1FA8A, 0x1FA8E, 0x1FAC8, 0x1FACD, 0x1FAEA, 0x1FAEF,
} };

inline bool driftstackMayStartEmoji17Sequence(std::span<const char16_t> characters, size_t offset = 0)
{
    if (offset > characters.size() || characters.size() - offset < 2)
        return false;
    char32_t lead = characters[offset];
    char32_t trail = characters[offset + 1];
    if (lead < 0xD800 || lead > 0xDBFF || trail < 0xDC00 || trail > 0xDFFF)
        return false;
    char32_t firstScalar = 0x10000 + ((lead - 0xD800) << 10) + (trail - 0xDC00);
    for (auto candidate : driftstackEmoji17FirstScalars) {
        if (candidate == firstScalar)
            return true;
    }
    return false;
}

inline bool driftstackMayStartEmoji17Sequence(StringView characters)
{
    return !characters.is8Bit() && driftstackMayStartEmoji17Sequence(characters.span16());
}

inline bool driftstackEmoji17SequenceMatchesAt(std::span<const char16_t> characters, size_t offset, std::u16string_view candidate)
{
    if (offset > characters.size() || candidate.size() > characters.size() - offset)
        return false;
    for (size_t i = 0; i < candidate.size(); ++i) {
        if (characters[offset + i] != candidate[i])
            return false;
    }
    return true;
}

inline size_t driftstackEmoji17SequenceLengthAt(std::span<const char16_t> characters, size_t offset)
{
    if (!driftstackMayStartEmoji17Sequence(characters, offset))
        return 0;
    size_t longestMatch = 0;
    for (auto candidate : driftstackEmoji17Sequences) {
        if (candidate.size() > longestMatch && driftstackEmoji17SequenceMatchesAt(characters, offset, candidate))
            longestMatch = candidate.size();
    }
    return longestMatch;
}

inline bool driftstackIsEmoji17Sequence(std::span<const char16_t> characters)
{
    if (!driftstackMayStartEmoji17Sequence(characters))
        return false;
    for (auto candidate : driftstackEmoji17Sequences) {
        if (candidate.size() == characters.size() && driftstackEmoji17SequenceMatchesAt(characters, 0, candidate))
            return true;
    }
    return false;
}

inline bool driftstackIsEmoji17Sequence(StringView characters)
{
    return !characters.is8Bit() && driftstackIsEmoji17Sequence(characters.span16());
}

// A draw run can contain adjacent grapheme clusters which all use the same
// bundled emoji face. Recognize only complete concatenations of the exact 163
// additions; mixed or partial text fails open to the ordinary shaping path.
inline size_t driftstackEmoji17SequenceRunCount(std::span<const char16_t> characters)
{
    if (characters.empty())
        return 0;
    size_t offset = 0;
    size_t count = 0;
    while (offset < characters.size()) {
        size_t longestMatch = driftstackEmoji17SequenceLengthAt(characters, offset);
        if (!longestMatch)
            return 0;
        offset += longestMatch;
        ++count;
    }
    return count;
}

inline size_t driftstackEmoji17SequenceRunCount(StringView characters)
{
    return characters.is8Bit() ? 0 : driftstackEmoji17SequenceRunCount(characters.span16());
}

enum class DriftstackAppleColorEmojiFace : uint8_t {
    None,
    Public,
    Ui,
};

inline DriftstackAppleColorEmojiFace driftstackAppleColorEmojiFace(CTFontRef font)
{
    if (!font)
        return DriftstackAppleColorEmojiFace::None;
    RetainPtr familyName = adoptCF(CTFontCopyFamilyName(font));
    if (!familyName)
        return DriftstackAppleColorEmojiFace::None;
    if (CFStringCompare(familyName.get(), CFSTR(".Apple Color Emoji UI"), kCFCompareCaseInsensitive) == kCFCompareEqualTo)
        return DriftstackAppleColorEmojiFace::Ui;
    if (CFStringCompare(familyName.get(), CFSTR("Apple Color Emoji"), kCFCompareCaseInsensitive) == kCFCompareEqualTo)
        return DriftstackAppleColorEmojiFace::Public;
    return DriftstackAppleColorEmojiFace::None;
}

inline bool driftstackIsBundledAppleColorEmojiFont(CTFontRef font)
{
    if (driftstackAppleColorEmojiFace(font) == DriftstackAppleColorEmojiFace::None)
        return false;
    RetainPtr<CFTypeRef> attribute = adoptCF(CTFontCopyAttribute(font, kCTFontURLAttribute));
    if (!attribute || CFGetTypeID(attribute.get()) != CFURLGetTypeID())
        return false;
    RetainPtr fileName = adoptCF(CFURLCopyLastPathComponent(static_cast<CFURLRef>(attribute.get())));
    return fileName && CFStringCompare(fileName.get(), CFSTR("AppleColorEmoji-160px.ttc"), kCFCompareCaseInsensitive) == kCFCompareEqualTo;
}

inline bool driftstackIsBundledAppleColorEmojiUIFont(CTFontRef font)
{
    return driftstackAppleColorEmojiFace(font) == DriftstackAppleColorEmojiFace::Ui
        && driftstackIsBundledAppleColorEmojiFont(font);
}

inline float driftstackPublicAppleColorEmojiAdvance(float pointSize)
{
    const unsigned pointPixelSize = static_cast<unsigned>(pointSize + 0.5f);
    if (pointPixelSize >= 26)
        return pointSize;
    switch (pointPixelSize) {
    case 8: return 11.f;
    case 9: return 12.f;
    case 10: return 13.f;
    case 11: return 15.f;
    case 12: return 16.f;
    case 13: return 17.f;
    case 14: return 19.f;
    case 15: return 20.f;
    case 16: return 21.f;
    case 17: return 22.f;
    case 18: return 22.f;
    case 19: return 23.f;
    case 20: return 23.f;
    case 21: return 23.f;
    case 22: return 24.f;
    case 23: return 24.f;
    case 24: return 25.f;
    case 25: return 26.f;
    default: return pointSize <= 12.f ? 16.f * (pointSize / 12.f) : pointSize;
    }
}

struct DriftstackEmojiUIGeometry {
    float advance { 0 };
    float ascent { 0 };
    float descent { 0 };
    float leading { 0 };

    explicit operator bool() const { return advance > 0; }
};

struct DriftstackEmojiUIGeometryCacheEntry {
    float pointSize { 0 };
    DriftstackEmojiUIGeometry geometry;
    bool initialized { false };
};

// Resolve a pre-Emoji-17 color scalar through the host system cascade. This
// yields the hidden `.Apple Color Emoji UI` face and, crucially, its contextual
// tracking. The bundled face1 has the same outlines but loses that UI geometry
// when materialized directly, so the host run is the canonical geometry probe.
inline DriftstackEmojiUIGeometry driftstackComputeSystemEmojiUIGeometry(float pointSize)
{
    RetainPtr systemFont = adoptCF(CTFontCreateUIFontForLanguage(kCTFontUIFontSystem, pointSize, nullptr));
    if (!systemFont)
        return { };

    static constexpr std::array<UniChar, 2> probeCharacters { 0xD83C, 0xDF89 }; // U+1F389 PARTY POPPER
    RetainPtr probeString = adoptCF(CFStringCreateWithCharacters(kCFAllocatorDefault, probeCharacters.data(), probeCharacters.size()));
    if (!probeString)
        return { };

    const void* attributeKeys[] = { kCTFontAttributeName };
    const void* attributeValues[] = { systemFont.get() };
    RetainPtr attributes = adoptCF(CFDictionaryCreate(kCFAllocatorDefault, attributeKeys, attributeValues, 1, &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks));
    RetainPtr attributedString = adoptCF(CFAttributedStringCreate(kCFAllocatorDefault, probeString.get(), attributes.get()));
    RetainPtr<CTLineRef> line;
    if (attributedString)
        line = adoptCF(CTLineCreateWithAttributedString(attributedString.get()));
    if (!line)
        return { };

    CFArrayRef runs = CTLineGetGlyphRuns(line.get());
    if (!runs || CFArrayGetCount(runs) != 1)
        return { };
    auto run = static_cast<CTRunRef>(CFArrayGetValueAtIndex(runs, 0));
    CFDictionaryRef runAttributes = CTRunGetAttributes(run);
    auto runFont = static_cast<CTFontRef>(CFDictionaryGetValue(runAttributes, kCTFontAttributeName));
    if (driftstackAppleColorEmojiFace(runFont) != DriftstackAppleColorEmojiFace::Ui)
        return { };

    CGFloat ascent = 0;
    CGFloat descent = 0;
    CGFloat leading = 0;
    double advance = CTLineGetTypographicBounds(line.get(), &ascent, &descent, &leading);
    if (!(advance > 0))
        return { };
    return {
        static_cast<float>(advance),
        static_cast<float>(ascent),
        static_cast<float>(descent),
        static_cast<float>(leading),
    };
}

inline DriftstackEmojiUIGeometry driftstackSystemEmojiUIGeometry(float pointSize)
{
    if (!(pointSize > 0))
        return { };

    // Font initialization, shaping, and painting ask for the same geometry in
    // tight succession. Keep a small bounded cache per rendering thread: it
    // avoids repeating the CoreText line construction, needs no cross-thread
    // lock, and cannot grow with attacker-controlled CSS font sizes.
    static thread_local std::array<DriftstackEmojiUIGeometryCacheEntry, 32> cache;
    static thread_local size_t nextSlot = 0;
    for (const auto& entry : cache) {
        if (entry.initialized && entry.pointSize == pointSize)
            return entry.geometry;
    }

    auto geometry = driftstackComputeSystemEmojiUIGeometry(pointSize);
    cache[nextSlot] = { pointSize, geometry, true };
    nextSlot = (nextSlot + 1) % cache.size();
    return geometry;
}

inline std::optional<float> driftstackEmoji17TargetAdvance(CTFontRef font, float pointSize)
{
    if (!driftstackEmoji17EnabledForCurrentArchetype()
        || !(pointSize > 0) || !driftstackIsBundledAppleColorEmojiFont(font))
        return std::nullopt;
    if (driftstackAppleColorEmojiFace(font) == DriftstackAppleColorEmojiFace::Public)
        return driftstackPublicAppleColorEmojiAdvance(pointSize);
    auto geometry = driftstackSystemEmojiUIGeometry(pointSize);
    if (geometry)
        return geometry.advance;
    return std::nullopt;
}

} // namespace WebCore
